name: React app deployement

on:
  push:
    branches: [ front ]
  pull_request:
    branches: [ front ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Deploy react app to github pages
      uses: tanwanimohit/deploy-react-to-ghpages@v1.0.1

    - name: Semantic Release
      env: 
        GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
      run: npx semantic-release